[package]
name = "eth-staking-smith"
version = "0.1.0-dev"
edition = "2021"
description = "Deposit CLI replacement library"
authors = ["tech@chorus.one"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "eth_staking_smith"
path = "src/lib.rs"

[dependencies]
clap = "^2.33"
derive_more = "0.15"
eth2_hashing = "0.3.0"
eth2_key_derivation = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
eth2_keystore = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
eth2_network_config = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e" }
eth2_ssz = "0.4.1"
eth2_wallet = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
ethereum-types = { version = "0.14.1", optional = true }
env_logger = "^0.6.0"
hex = "0.4"
lazy_static = "1.4"
log = "^0.4"
getrandom = "0.2"
regex = "1.5.5"
serde = "1.0.115"
serde_derive = "1.0"
serde_json = "1.0"

ssz-rs = { git = "https://github.com/ChorusOne/ssz-rs.git", rev = "cb08f18ca919cc1b685b861d0fa9e2daabe89737" }
ssz-rs-derive = { git = "https://github.com/ChorusOne/ssz-rs.git", rev = "cb08f18ca919cc1b685b861d0fa9e2daabe89737" }
tiny-bip39 = "^0.8.0"
tree_hash = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
types = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
uuid = { version = "0.8.1", features = ["v4"] }

[patch.crates-io]
eth2_hashing = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
eth2_serde_utils = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
eth2_ssz = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
eth2_ssz_derive = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
eth2_ssz_types = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
tree_hash = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}
tree_hash_derive = { git = "https://github.com/ChorusOne/lighthouse", rev = "ef90a15aae791435a4180d7e6bc1d8e29ced6e2e"}

[dev-dependencies]
test-log = "^0.2"
pretty_assertions = "^1.2"
assert_cmd = "2.0"
predicates = "2.1"

[[test]]
name = "e2e-tests"
path = "tests/lib.rs"
