[package]
name = "eth-staking-smith"
version = "0.1.0-dev"
edition = "2021"
description = "Deposit CLI replacement library"
authors = ["tech@chorus.one"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "eth_staking_smith"
path = "src/lib.rs"

[dependencies]
clap = "^2.33"
eth2_keystore = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_network_config = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_wallet = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
env_logger = "^0.6.0"
hex = "0.4"
lazy_static = "^1.4"
log = "^0.4"
rand = "^0.8"
serde = "1.0.115"
serde_derive = "1.0"
serde_json = "1.0"
tiny-bip39 = "^0.8.0"
tree_hash = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
types = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
uuid = { version = "0.8.1", features = ["v4"] }

[patch.crates-io]
eth2_hashing = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_serde_utils = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_ssz = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_ssz_types = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
tree_hash = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}

[dev-dependencies]
test-log = "^0.2"
pretty_assertions = "^1.2"
