[package]
name = "eth-staking-smith"
version = "0.1.0-dev"
edition = "2021"
description = "Deposit CLI replacement library"
authors = ["tech@chorus.one"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "eth_staking_smith"
path = "src/lib.rs"

[dependencies]
clap = "^2.33"
ethereum_hashing = "1.0.0-beta.2"
eth2_key_derivation = { git = "https://github.com/ChorusOne/lighthouse", rev = "441fc1691b69f9edc4bbdc6665f3efab16265c9b"}
eth2_keystore = { git = "https://github.com/ChorusOne/lighthouse", rev = "441fc1691b69f9edc4bbdc6665f3efab16265c9b"}
eth2_network_config = { git = "https://github.com/ChorusOne/lighthouse", rev = "441fc1691b69f9edc4bbdc6665f3efab16265c9b" }
ethereum_ssz = "0.5.3"
eth2_wallet = { git = "https://github.com/ChorusOne/lighthouse", rev = "441fc1691b69f9edc4bbdc6665f3efab16265c9b"}
ethereum-types = { version = "0.14.1", optional = true }
env_logger = "^0.10.0"
hex = "0.4"
lazy_static = "1.4"
log = "^0.4"
getrandom = "0.2"
regex = "1.9.3"
serde = "1.0.185"
serde_derive = "1.0"
serde_json = "1.0"
ssz-rs = { git = "https://github.com/ChorusOne/ssz-rs.git", rev = "cb08f18ca919cc1b685b861d0fa9e2daabe89737" }
ssz-rs-derive = { git = "https://github.com/ChorusOne/ssz-rs.git", rev = "cb08f18ca919cc1b685b861d0fa9e2daabe89737" }
tiny-bip39 = "^0.8.0"
tree_hash = "0.5.2"
types = { git = "https://github.com/ChorusOne/lighthouse", rev = "441fc1691b69f9edc4bbdc6665f3efab16265c9b"}
uuid = { version = "1.4", features = ["v4"] }

[dev-dependencies]
test-log = "^0.2"
pretty_assertions = "^1.4"
assert_cmd = "2.0"
predicates = "3.0"

[[test]]
name = "e2e-tests"
path = "tests/lib.rs"
