name: CI

# This workflow run tests and build for each push

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version      

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build --release


  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: EmbarkStudios/cargo-deny-action@v1
